import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  SunOutline,
  MoonOutline,
  ShopOutline,
  ShoppingCartOutline,
  DeleteOutline,
  MinusOutline,
  PlusOutline,
  HomeOutline,
  UserOutline,
  LockOutline,
  SettingOutline
} from '@ant-design/icons-angular/icons';

export const icons = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  SunOutline,
  MoonOutline,
  ShopOutline,
  ShoppingCartOutline,
  DeleteOutline,
  PlusOutline,
  MinusOutline,
  HomeOutline,
  UserOutline,
  LockOutline,
  SettingOutline,
];
